test: bump min mender version
mendersoftware/meta-mender pull request #1157
Opened 2020-10-28 09:44 UTC by oleorhagen

The fix for the sudo bug is on the released Mender-Artifact 3.4.x branch, but is
not yet released, meaning that it is not in the 3.4.0 tag in Mender-Artifact:

https://github.com/mendersoftware/mender-artifact/commits/3.4.0

Therefore, this will only be in master and be released with Mender release 2.6.0

2020-10-28 09:49 UTC, oleorhagen commented
I do _think_ this is right

2020-10-28 09:57 UTC, oleorhagen commented
Client version it is.

2020-10-28 09:57 UTC, lluiscampos requested changes
> I do _think_ this is right. or should it be `2.5.0` client version?

If any, it should be 2.5.0 client version, yes.

But I think it is about time to introduce `min_mender_artifact_version` fixture. If you look at the code for `min_mender_version`, you will see that it is quite straight forward to have a similar one for mender-artifact, as we can always find out the version of the tool in the yocto build (it won't work for mender-convert tests, but that we don't need to worry about now).


(related)
I also realized that [here](https://github.com/mendersoftware/meta-mender/blob/master/tests/acceptance/fixtures.py#L465) we query for `mender` instead of `mender-client`. This works just because in [here](https://github.com/mendersoftware/mender-qa/blob/master/scripts/jenkins-yoctobuild-build.sh#L143) we set both, but we should correct the fixture anyway. -> Let me follow-up on this independently, as I suspect needs a fix in `mender-convert` too.

2020-10-28 11:57 UTC, oleorhagen commented
The recipe renaming has had some funny reprecussions

2020-10-28 12:40 UTC, oleorhagen commented
> (related)
> I also realized that [here](https://github.com/mendersoftware/meta-mender/blob/master/tests/acceptance/fixtures.py#L465) we query for `mender` instead of `mender-client`. This works just because in [here](https://github.com/mendersoftware/mender-qa/blob/master/scripts/jenkins-yoctobuild-build.sh#L143) we set both, but we should correct the fixture anyway. -> Let me follow-up on this independently, as I suspect needs a fix in `mender-convert` too.

I did add it here: https://github.com/mendersoftware/meta-mender/pull/1158/commits/aa406d8a9102a176d4151b428ca3c6651a01fdcb

Should I remove it?

2020-10-28 12:44 UTC, lluiscampos commented
> > (related)
> > I also realized that [here](https://github.com/mendersoftware/meta-mender/blob/master/tests/acceptance/fixtures.py#L465) we query for `mender` instead of `mender-client`. This works just because in [here](https://github.com/mendersoftware/mender-qa/blob/master/scripts/jenkins-yoctobuild-build.sh#L143) we set both, but we should correct the fixture anyway. -> Let me follow-up on this independently, as I suspect needs a fix in `mender-convert` too.
> 
> I did add it here: [aa406d8](https://github.com/mendersoftware/meta-mender/commit/aa406d8a9102a176d4151b428ca3c6651a01fdcb)
> 
> Should I remove it?

No, is okey. Thanks.

2020-11-23 09:50 UTC, lluiscampos approved these changes

2020-11-23 12:20 UTC, merged