Add the update control variables to the demo configuration
mendersoftware/meta-mender pull request #1415
Opened 2021-07-01 12:22 UTC by oleorhagen

This adds the possibility to configure the udpate control configuration
variables in 'mender.conf'.

This is done through adding:

* MENDER_UPDATE_CONTROL_MAP_EXPIRATION_TIME_SECONDS
* MENDER_UPDATE_CONTROL_MAP_BOOT_EXPIRATION_TIME_SECONDS

variables, which, if set, are added to the rootfs local configuration file in
/etc/mender/mender.conf.

It also adds a default value for these variables in the demo layer, in which the
values are set to 90 and 45, respectively.

Changelog: Add `MENDER_UPDATE_CONTROL_MAP_EXPIRATION_TIME_SECONDS`
`MENDER_UPDATE_CONTROL_MAP_BOOT_EXPIRATION_TIME_SECONDS` as configuration
variables, which set the values of `UpdateControlMapExpirationTimeSeconds`, and
`UpdateControlMapBootExpirationTimeSeconds`, in `mender.conf`.

Signed-off-by: Ole Petter <ole.orhagen@northern.tech>

# External Contributor Checklist

🚨 Please review the [guidelines for contributing](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md) to this repository.

- [ ] Make sure that all commits have a [`Changelog`](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md#changelog-tags) tag. If nothing should be added to the Changelog, add a `Changelog: None` tag. If there is a change, add `Changelog: Commit`, or `Changelog: Title`, depending on what should be included in the changelog.

- [ ] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.

### Description

Please describe your pull request.

Thank you!

2021-07-01 13:10 UTC, lluiscampos requested changes
Thanks for taking this.

Two remarks:

* Should we align the values with https://github.com/mendersoftware/meta-mender/pull/1416/files ?
* Good changelog message, but we should slightly extend it (or create a new one?) to say that we are setting them to 90/45 (or whatever we decide on) for `meta-mender-demo`.

See comment also.

2021-07-01 13:10 UTC, lluiscampos commented on meta-mender-demo/recipes-mender/mender-client/mender-client_%.bbappend
> +MENDER_UPDATE_CONTROL_MAP_BOOT_EXPIRATION_TIME_SECONDS = "45"
```suggestion
MENDER_UPDATE_CONTROL_MAP_EXPIRATION_TIME_SECONDS_mender-client-install = "90"
MENDER_UPDATE_CONTROL_MAP_BOOT_EXPIRATION_TIME_SECONDS_mender-client-install = "45"
```

2021-07-01 13:19 UTC, oleorhagen commented
> Thanks for taking this.
> 
> Two remarks:
> 
>     * Should we align the values with https://github.com/mendersoftware/meta-mender/pull/1416/files ?

Yes, I was expecting a comment here. I was planning on just making a new commit, depending on which one is merged first.

> 
>     * Good changelog message, but we should slightly extend it (or create a new one?) to say that we are setting them to 90/45 (or whatever we decide on) for `meta-mender-demo`.

Good point. Adding it to the `Changelog`.
> 
> 
> See comment also.

2021-07-01 13:23 UTC, oleorhagen commented
Holding off the merge pending: https://github.com/mendersoftware/meta-mender/pull/1416

2021-07-05 13:32 UTC, kacf approved these changes
Conclusion after live chat: Accept this, but leave it undocumented and remove changelog. We prefer that people use the mechanism of adding a custom `mender.conf` to the mender-client recipe, instead of having a new variable for every setting. But since we cannot use this mechanism ourselves (it would conflict if the user also does it), we need these variables for our demo layer.

2021-07-05 19:12 UTC, lluiscampos commented
Rebased on top of latest master.

@mender-test-bot start pipeline :baseball:

2021-07-05 19:28 UTC, lluiscampos commented
@mender-test-bot start pipeline :rugby_football:

2021-07-06 13:52 UTC, lluiscampos approved these changes

2021-07-06 13:53 UTC, merged