Fix FTBFS due to host contamination with secure boot enabled
mendersoftware/meta-mender pull request #1511
Opened 2021-11-04 07:47 UTC by phatina

meta-secure-core defines `password.inc` which triggers an error if I want to use secure boot:

```
meta-secure-core defines password.inc which triggers an error:
Path ./package/boot/efi/EFI/BOOT/password.inc.p7b is owned by uid 1000,
gid 1000, which doesn't match any user/group on target. This may be due
to host contamination.
```

Removing `password.inc` file fixes this.

Please, review. Thanks.

2021-11-04 08:42 UTC, kacf requested changes
Thanks! The code looks good to me, but can you please submit this to the master branch? We always merge there first, and then cherry-pick backwards from there.

2021-11-04 10:40 UTC, phatina commented
> Thanks! The code looks good to me, but can you please submit this to the master branch? We always merge there first, and then cherry-pick backwards from there.

Oh, sure thing. Will do. Thanks

2021-11-04 10:45 UTC, phatina commented
Done, see #1512. Thanks.

2021-11-05 07:35 UTC, kacf commented
Closing this, the fix will be cherry-picked from master separately.

2021-11-05 07:35 UTC, closed without merging

2021-11-05 19:49 UTC, phatina commented
> Closing this, the fix will be cherry-picked from master separately.

Can you cherry pick this change from master to dunfell, please? So that I can rebase in my project. Thanks!

2021-11-09 07:54 UTC, kacf commented
Fixed in #1515.