lsb-ld: Avoid lib64/*.a issues on multilib systems
mendersoftware/meta-mender pull request #1605
Opened 2022-02-23 19:00 UTC by leon-anavi

Fix do_install for x86-64 to avoid issues with ./lib64/*.a and
missing arent directory structure during do_package on multilib
systems.

Signed-off-by: Leon Anavi <leon.anavi@konsulko.com>

# External Contributor Checklist

🚨 Please review the [guidelines for contributing](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md) to this repository.

- [ ] Make sure that all commits have a [`Changelog`](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md#changelog-tags) tag. If nothing should be added to the Changelog, add a `Changelog: None` tag. If there is a change, add `Changelog: Commit`, or `Changelog: Title`, depending on what should be included in the changelog.

- [ ] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.

### Description

Please describe your pull request.

Thank you!

2022-02-23 19:05 UTC, leon-anavi commented
The following warnings and errors are avoided with the provided patch:
```
WARNING: lsb-ld-1.0-r0 do_package: FILES contains file '/lib64/*.a' which resides under a directory symlink. Please fix the recipe and use the real path for the file.
ERROR: lsb-ld-1.0-r0 do_package: File './lib64/*.a' cannot be packaged into 'lsb-ld-staticdev' because its parent directory structure does not exist. One of its parent directories is a symlink whose target directory is not included in the package.
```

This issues appears on `x86-64` machines such as `intel-corei7-64` from `meta-intel` while using the Multilib feature and with enabled Mender delta-update support. Here are a couple of code snippets from `local.conf` to reproduce the issue:

```
require conf/multilib.conf
MULTILIBS = "multilib:lib32"
DEFAULTTUNE_virtclass-multilib-lib32 = "x86"
```

```
IMAGE_INSTALL_append = " mender-binary-delta"
LICENSE_FLAGS_WHITELIST_append = " commercial_mender-binary-delta"
FILESEXTRAPATHS_prepend_pn-mender-binary-delta := "${HOME}/mender-binary-delta/:"
```

Best regards,
Leon

2022-02-24 08:48 UTC, kacf requested changes
Hey @leon-anavi, the code looks good to me! But can I request that you add a `Changelog: Title` tag to your commit message?

2022-02-24 08:58 UTC, leon-anavi commented
> Hey @leon-anavi, the code looks good to me! But can I request that you add a `Changelog: Title` tag to your commit message?

Yes, sure, I have added it.

Best regards,
Leon

2022-02-24 09:05 UTC, kacf approved these changes
Thank you!

2022-03-02 10:08 UTC, kacf commented
Only spurious failures, merging this. Thanks!

2022-03-02 10:08 UTC, merged