MEN-5221: add the new control map endpoint to the mock-server
mendersoftware/meta-mender pull request #1653
Opened 2022-04-01 13:51 UTC by oleorhagen

Changelog: None
Signed-off-by: Ole Petter <ole.orhagen@northern.tech>

2022-04-01 13:52 UTC, oleorhagen commented
Needed for the client PR https://github.com/mendersoftware/mender/pull/975

2022-04-04 06:40 UTC, kacf requested changes

2022-04-04 06:40 UTC, kacf commented on tests/meta-mender-ci/recipes-testing/mender-mock-server/files/mender-mock-server.py
> +                self.send_empty_response(204)
This endpoint [cannot return 204](https://github.com/mendersoftware/deployments-enterprise/blob/master/docs/devices_api_v2.yml#L127-L140). It should return 404 in that case (there is no map). In this case the client should not call it at all, but it's good to have it verified.

2022-04-07 06:54 UTC, kacf approved these changes

2022-04-11 09:13 UTC, merged

2022-04-11 09:17 UTC, oleorhagen commented
@mender-test-bot cherry-pick to: `dunfell`