Master f2fs fix
mendersoftware/meta-mender pull request #1664
Opened 2022-04-12 14:54 UTC by leon-anavi

# External Contributor Checklist

🚨 Please review the [guidelines for contributing](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md) to this repository.

- [X] Make sure that all commits have a [`Changelog`](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md#changelog-tags) tag. If nothing should be added to the Changelog, add a `Changelog: None` tag. If there is a change, add `Changelog: Commit`, or `Changelog: Title`, depending on what should be included in the changelog.

- [X] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.

### Description

This pull request brings a couple of improvements and bug fixes related to F2FS:

* Add a dependency to f2fs-tools-native in `mender-part-images` if using F2FS for the data partition.
* Load Mender configuration files to the data partition when using F2FS through `sload.f2fs` in class `dataimg`.

2022-04-21 07:23 UTC, kacf requested changes
I'd change to `Changelog: Commit` on both of these commits, since they are bug fixes.

2022-04-21 07:23 UTC, kacf commented on meta-mender-core/classes/mender-dataimg.bbclass
> +        $volume_label_flag data \
Why remove `${MENDER_DATA_PART_LABEL}`?

2022-04-21 08:53 UTC, leon-anavi commented
Hi @kacf,

> I'd change to `Changelog: Commit` on both of these commits, since they are bug fixes.

Following your feedback I have made the required modifications in the code and the git commit message. Thank you for the code review. Is the new version of the pull request OK?

Thanks,
Leon

2022-04-22 07:18 UTC, kacf approved these changes
Yes, thank you! I'll run this through our full test suite now.

2022-04-26 08:34 UTC, kacf commented
Just spurious failures.

2022-04-26 08:34 UTC, merged