meta-mender-raspberrypi: fix outdated README
mendersoftware/meta-mender pull request #1669
Opened 2022-04-22 11:25 UTC by TheYoctoJester

Changelog: none

Signed-off-by: Josef Holzmayr <jester@theyoctojester.info>

# External Contributor Checklist

🚨 Please review the [guidelines for contributing](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md) to this repository.

- [ ] Make sure that all commits have a [`Changelog`](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md#changelog-tags) tag. If nothing should be added to the Changelog, add a `Changelog: None` tag. If there is a change, add `Changelog: Commit`, or `Changelog: Title`, depending on what should be included in the changelog.

- [ ] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.

### Description

Please describe your pull request.

Thank you!

2022-04-25 06:42 UTC, tranchitella approved these changes

2022-04-25 07:03 UTC, kacf requested changes

2022-04-25 07:03 UTC, kacf commented on meta-mender-raspberrypi/README.md
> +        MENDER_FEATURES_DISABLE_append = " mender-grub mender-image-uefi"
This is not necessary, the layer [does it for you](https://github.com/mendersoftware/meta-mender/blob/master/meta-mender-raspberrypi/conf/layer.conf#L19-L21) (indirectly).

2022-04-26 08:30 UTC, kacf approved these changes

2022-04-26 08:33 UTC, merged