fix: Do not provide the mender-client 3.3.1 as the branch default
mendersoftware/meta-mender pull request #1870
Opened 2022-12-19 08:04 UTC by oleorhagen

Ticket: None
Changelog: None

Signed-off-by: Ole Petter <ole.orhagen@northern.tech>

2022-12-19 08:05 UTC, oleorhagen commented
Skipped the `Changelog` here. Not sure if we want it or not. Feel free to correct me.

2022-12-19 08:24 UTC, tranchitella approved these changes

2022-12-19 09:31 UTC, lluiscampos requested changes
> Skipped the `Changelog` here. Not sure if we want it or not. Feel free to correct me.

This requires a changelog entry and a release ASAP (I can follow-up on that :runner:).

The reasoning goes in that it is a "regression" to have changed the default version that we now install for `dunfell`. We have bumped my mistake the major version of mender (client). On top of it we have done this for mender (client) and not mender-artifact, which is it even working?

2022-12-19 12:16 UTC, lluiscampos approved these changes

2022-12-20 20:09 UTC, lluiscampos commented
Builds:
* For Mender 3.4.0 @ [Pipeline 727810534](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/727810534)
* For Mender 3.3.1 @ [Pipeline 727866241](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/727866241)

2022-12-22 09:40 UTC, lluiscampos commented
> Builds:
> 
>     * For Mender 3.4.0 @ [Pipeline 727810534](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/727810534)
> 
>     * For Mender 3.3.1 @ [Pipeline 727866241](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/727866241)

The builds look good. Failures:
* `TestAzureIoTHubDeviceLifecycle` backend test failing for both: the fix has not yet been released
* `test_regular_protocol_commands`, `test_filetransfer_limits_upload` and `test_bogus_proto_message` failing for 3.4.0: known issues or test robustness improvements not ported to release branches.

2022-12-22 09:40 UTC, merged