[scarthgap] chase persistent machine id renames
mendersoftware/meta-mender pull request #2158
Opened 2024-08-10 01:09 UTC by zach-welch-aquabyte

Commit bca6bf7 included part of the required fixed.  This contains the rest. There may be others, but this allows me to build the C++ client.

Left as an exercise for the maintainers: enabling this features somewhere in the official test matrix, so this kind of breakage gets detected sooner. :grin:

2024-08-12 09:28 UTC, TheYoctoJester commented
@lluiscampos I think we should rather cherry-pick https://github.com/mendersoftware/meta-mender/commit/2a58af7b129907f89ab9c5fc3c595db983c14a23 here?

2024-08-12 10:01 UTC, lluiscampos requested changes
> @lluiscampos I think we should rather cherry-pick [2a58af7](https://github.com/mendersoftware/meta-mender/commit/2a58af7b129907f89ab9c5fc3c595db983c14a23) here?

@TheYoctoJester The commit you are referring to was cherry-picked (and released). The cherry-pick is the `bca6bf...` that the author is referring to, which is an incomplete fix.

> Commit [bca6bf7](https://github.com/mendersoftware/meta-mender/commit/bca6bf71fb18bb85648cb656ca9343a480e0dc58) included part of the required fixed. This contains the rest. There may be others, but this allows me to build the C++ client.
> 

Thank you @zach-welch-aquabyte. I don't see any other reference to `mender-client-* `, so it should be fine now.

> Left as an exercise for the maintainers: enabling this features somewhere in the official test matrix, so this kind of breakage gets detected sooner. 😁

I apologize with the mess around this feature. As you well noted we don't have it in our test matrix. We'll consider adding this and other features in the future.

@zach-welch-aquabyte Can you modify the changelog entry? Reusing the commit title in this instance results in a not too user friendly text. I think it would read much better something like "Complete fix for persistent machine id support files renamed. Commit bca6bf71fb18bb85648cb656ca9343a480e0dc58 attempted to fix the issue but some references went missing. This commit addresses the rest"

2024-08-15 11:34 UTC, lluiscampos approved these changes

2024-08-15 11:36 UTC, lluiscampos commented
Hi @zach-welch-aquabyte and thanks for amending your commit. I took the liberty to amend another formality (setting `Changelog: Commit`) and force-pushed to your fork. I hope that you don't mind.

I'll now run the CI pipeline and merge as soon as possible.

Thanks again for your contribution :rocket:

2024-08-15 11:36 UTC, lluiscampos commented
@mender-test-bot start pipeline

2024-08-16 09:44 UTC, lluiscampos commented
The failing test is due to a missing test fix. See:
* https://github.com/mendersoftware/meta-mender/pull/2151

Merging!

2024-08-16 09:44 UTC, merged

2024-08-16 09:44 UTC, lluiscampos commented
@mender-test-bot cherry-pick to:
* master